# Generated by Django 2.2.13 on 2020-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
